"""sync models after backend consistency

Revision ID: 71821fb166e1
Revises: 922172f78a6c
Create Date: 2026-07-14 10:18:30.426168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71821fb166e1'
down_revision = '922172f78a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
